linters:
  enable-all: true
  disable:
    - wsl
    - gomnd
    - testpackage
    - wrapcheck
    - nlreturn
    - goerr113
    - exhaustivestruct
    - exhaustive
    - cyclop
    - funlen

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - goconst
        - funlen
        - scopelint
        - gocognit
        - paralleltest
        - errorlint
        - forcetypeassert
    - path: doc\.go
      linters:
        - lll